oe-selftest: wic fix deps of test_efi_plugin_unified_kernel_image_qemu
oe-selftest wic.Wic2.test_efi_plugin_unified_kernel_image_qemu failed
with:
  AssertionError: Command
    'bitbake  core-image-minimal core-image-minimal-initramfs ovmf'
    returned non-zero exit status 1:

bitbake reported:
  FileNotFoundError: [Errno 2] No such file or directory:
  '.../build-st-242167/tmp/deploy/images/qemux86-64/core-image-minimal-initramfs-qemux86-64.cpio.gz'
  WARNING: .../build-st-242167/tmp/work/qemux86_64-poky-linux/core-image-minimal/1.0/temp/run.do_image_wic.986859:162
    exit 1 from 'BUILDDIR="/home/adrian/projets/oss/poky/build-st-242167" PSEUDO_UNLOAD=1
    wic create "$wks" --vars ".../build-st-242167/tmp/sysroots/qemux86-64/imgdata/"
       -e "core-image-minimal" -o "$build_wic/" -w "$tmp_wic"'

Creating a configuration as the test does and calling
  bitbake -g core-image-minimal
does not show a dependency from core-image-minimal:do_image_wic on
core-image-minimal-initramfs:do_image_complete.
Adding the dependency directly to the test case resolves the issue.

Since the dependency is basically created by the wks file solving this
in a more generic way, e.g. by handling the dependency in
image_types_wic.bbclass does not look like simple.

(From OE-Core rev: 442e7b3aef844803acab85923d5f9242bc8be485)

Signed-off-by: Adrian Freihofer <adrian.freihofer@siemens.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>